# Generated by Django 3.1.7 on 2021-04-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasaction',
            new_name='Transaction',
        ),
    ]
